#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Regression test for `hipfire update` dirty-working-tree bug.
#
# Before the fix, cli/index.ts ran `git pull origin main` which aborts with
#   "Your local changes to the following files would be overwritten by merge"
# whenever a tracked file (notably Cargo.lock, which cargo build can rewrite
# across cargo versions) is modified in the working tree.
#
# This test sets up a fake upstream + fake local clone, dirties Cargo.lock
# and Cargo.toml in the clone (matching the exact error the user reported),
# then exercises the fix's git sequence end-to-end. It asserts:
#   1. The update flow exits successfully (no merge abort)
#   2. Cargo.toml is now at upstream HEAD (actual update occurred)
#   3. The user's dirty changes are preserved in a named stash
#   4. The working tree is clean afterwards
#
# The test runs entirely in a tmp dir and never touches the real repo.

set -euo pipefail

TEST_NAME="update-dirty-tree"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

fail() { echo "FAIL [$TEST_NAME]: $*" >&2; exit 1; }
pass() { echo "PASS [$TEST_NAME]: $*"; }

# ── 1. Build a fake upstream + seed it ──────────────────────────────────
UPSTREAM="$TMPDIR/upstream.git"
SEED="$TMPDIR/seed"
LOCAL="$TMPDIR/local"

git init --quiet --bare "$UPSTREAM"
git init --quiet "$SEED"
git -C "$SEED" config user.email test@example.com
git -C "$SEED" config user.name  "Test"
git -C "$SEED" checkout -q -b main

cat > "$SEED/Cargo.toml" <<'EOF'
[workspace]
version = "0.1.0"
EOF
cat > "$SEED/Cargo.lock" <<'EOF'
# Automatically @generated by Cargo.
version = 3
EOF
echo "fn main() {}" > "$SEED/main.rs"

git -C "$SEED" add .
git -C "$SEED" commit --quiet -m "initial"
git -C "$SEED" remote add origin "$UPSTREAM"
git -C "$SEED" push --quiet origin main
git -C "$UPSTREAM" symbolic-ref HEAD refs/heads/main

# ── 2. Clone "locally" (simulates a hipfire install) ────────────────────
git clone --quiet "$UPSTREAM" "$LOCAL"
git -C "$LOCAL" config user.email test@example.com
git -C "$LOCAL" config user.name  "Test"

# ── 3. Publish a new upstream commit (what `hipfire update` should pull) ─
cat > "$SEED/Cargo.toml" <<'EOF'
[workspace]
version = "0.1.1"
EOF
echo "fn main() { println!(\"updated\"); }" > "$SEED/main.rs"
git -C "$SEED" add .
git -C "$SEED" commit --quiet -m "upstream update"
git -C "$SEED" push --quiet origin main

# ── 4. Dirty the local clone exactly as the user reported ───────────────
# Cargo.lock gets rewritten by `cargo build` when the lockfile format
# version diverges from the committed one. Cargo.toml can drift on Windows
# checkouts due to autocrlf, or be edited by users experimenting locally.
cat > "$LOCAL/Cargo.lock" <<'EOF'
# Automatically @generated by Cargo.
version = 4
EOF
cat > "$LOCAL/Cargo.toml" <<'EOF'
[workspace]
version = "0.1.0"
# user scribble
EOF

# Sanity: before the fix, `git pull origin main` inside $LOCAL aborts
# with exactly the reported error. Capture that to prove we're reproducing
# the bug. We don't fail the test here — just document it.
if git -C "$LOCAL" pull origin main 2>"$TMPDIR/pull.err" 1>/dev/null; then
    fail "baseline reproduction failed: plain 'git pull' unexpectedly succeeded with a dirty tree"
fi
grep -q "local changes to the following files would be overwritten" "$TMPDIR/pull.err" \
    || fail "baseline reproduction didn't hit the reported error; saw: $(cat "$TMPDIR/pull.err")"

# ── 5. Exercise the FIXED update sequence ───────────────────────────────
# This mirrors the post-fix logic in cli/index.ts. If cli/index.ts diverges
# from this sequence, this test will need to be updated in lockstep.
# Return codes:
#   0  = updated
#   10 = refused (not requested ref)
#   11 = refused (local commits ahead)
#   20 = git operation failed
update_flow() {
    local repo="$1"
    local requested_ref="${2:-main}"
    local branch
    branch="$(git -C "$repo" rev-parse --abbrev-ref HEAD)"
    if [ "$branch" != "$requested_ref" ] && [ "$branch" != "HEAD" ]; then
        echo "refusing: branch is $branch, not $requested_ref" >&2
        return 10
    fi
    git -C "$repo" fetch origin "$requested_ref" --quiet || return 20
    local fetched
    fetched="$(git -C "$repo" rev-parse --verify FETCH_HEAD)" || return 20
    local ahead
    ahead="$(git -C "$repo" rev-list --count "$fetched..HEAD" 2>/dev/null || echo 0)"
    if [ "${ahead:-0}" -gt 0 ]; then
        echo "refusing: local checkout has $ahead unpushed commit(s)" >&2
        return 11
    fi
    if [ -n "$(git -C "$repo" status --porcelain)" ]; then
        local ts
        ts="$(date -u +%Y-%m-%dT%H-%M-%SZ)"
        git -C "$repo" stash push --include-untracked -m "hipfire-update-$ts" --quiet || return 20
    fi
    git -C "$repo" reset --hard "$fetched" --quiet || return 20
}

update_flow "$LOCAL" || fail "fixed update_flow exited non-zero ($?)"

# ── 6. Assert post-conditions ──────────────────────────────────────────
grep -q '0.1.1' "$LOCAL/Cargo.toml" \
    || fail "Cargo.toml was not updated to upstream HEAD (still: $(cat "$LOCAL/Cargo.toml" | tr '\n' ' '))"

grep -q 'println' "$LOCAL/main.rs" \
    || fail "main.rs was not updated to upstream HEAD"

[ -z "$(git -C "$LOCAL" status --porcelain)" ] \
    || fail "working tree is dirty after update"

stash_count="$(git -C "$LOCAL" stash list | wc -l)"
[ "$stash_count" -ge 1 ] \
    || fail "expected at least one stash entry, got $stash_count"

git -C "$LOCAL" stash list | grep -q 'hipfire-update-' \
    || fail "stash entry missing 'hipfire-update-' marker"

# ── 7. Edge cases ──────────────────────────────────────────────────────

# 7a. Clean tree (no-op dirty path): should succeed and produce no stash
LOCAL_CLEAN="$TMPDIR/local-clean"
git clone --quiet "$UPSTREAM" "$LOCAL_CLEAN"
git -C "$LOCAL_CLEAN" config user.email test@example.com
git -C "$LOCAL_CLEAN" config user.name  "Test"
# Make upstream advance once more so there's something to pull
cat > "$SEED/main.rs" <<'EOF'
fn main() { println!("second update"); }
EOF
git -C "$SEED" add main.rs
git -C "$SEED" commit --quiet -m "second upstream update"
git -C "$SEED" push --quiet origin main
update_flow "$LOCAL_CLEAN" || fail "clean-tree update_flow exited non-zero ($?)"
grep -q 'second update' "$LOCAL_CLEAN/main.rs" \
    || fail "clean-tree update didn't pull the second upstream commit"
[ "$(git -C "$LOCAL_CLEAN" stash list | wc -l)" -eq 0 ] \
    || fail "clean-tree update created a stash when it shouldn't have"

# 7b. Feature branch guard: should refuse with code 10
LOCAL_DEV="$TMPDIR/local-dev"
git clone --quiet "$UPSTREAM" "$LOCAL_DEV"
git -C "$LOCAL_DEV" config user.email test@example.com
git -C "$LOCAL_DEV" config user.name  "Test"
git -C "$LOCAL_DEV" checkout --quiet -b my-feature
set +e
update_flow "$LOCAL_DEV"
dev_rc=$?
set -e
[ "$dev_rc" -eq 10 ] || fail "feature-branch guard returned $dev_rc, expected 10"

# 7c. Unpushed-commits guard: should refuse with code 11
LOCAL_AHEAD="$TMPDIR/local-ahead"
git clone --quiet "$UPSTREAM" "$LOCAL_AHEAD"
git -C "$LOCAL_AHEAD" config user.email test@example.com
git -C "$LOCAL_AHEAD" config user.name  "Test"
echo "local-only change" > "$LOCAL_AHEAD/local_only.txt"
git -C "$LOCAL_AHEAD" add local_only.txt
git -C "$LOCAL_AHEAD" commit --quiet -m "local-only commit"
set +e
update_flow "$LOCAL_AHEAD"
ahead_rc=$?
set -e
[ "$ahead_rc" -eq 11 ] || fail "ahead-commits guard returned $ahead_rc, expected 11"
# And the local commit must still be intact
grep -q 'local-only change' "$LOCAL_AHEAD/local_only.txt" \
    || fail "ahead-commits guard clobbered the local commit"

# 7d. Immutable commit pin: a detached install may intentionally remain on
# an older commit even when the upstream branch has advanced.
LOCAL_PINNED="$TMPDIR/local-pinned"
git clone --quiet "$UPSTREAM" "$LOCAL_PINNED"
PINNED_COMMIT="$(git -C "$SEED" rev-list --max-parents=0 HEAD)"
git -C "$LOCAL_PINNED" checkout --quiet --detach "$PINNED_COMMIT"
update_flow "$LOCAL_PINNED" "$PINNED_COMMIT" \
    || fail "immutable-ref update_flow exited non-zero ($?)"
[ "$(git -C "$LOCAL_PINNED" rev-parse HEAD)" = "$PINNED_COMMIT" ] \
    || fail "immutable-ref update moved away from pinned commit"

# ── 8. Divergence guard ────────────────────────────────────────────────
# The update_flow() above mirrors the logic in cli/index.ts. If someone
# reverts cli/index.ts back to a plain `git pull`, this test still passes
# (because update_flow is independent). Catch that by asserting the key
# pieces of the fix are still present in cli/index.ts itself.
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "")"
if [ -z "$REPO_ROOT" ]; then
    # Running from an extracted tarball or CI without a checkout; skip.
    echo "  (divergence guard skipped: not in a git checkout)"
else
    CLI="$REPO_ROOT/cli/index.ts"
    [ -f "$CLI" ] || fail "cli/index.ts not found at $CLI"

    # Required: the fix must be present. Each marker is checked
    # independently so multi-line formatting doesn't break us.
    grep -q '"stash", "push", "--include-untracked"' "$CLI" \
        || fail "cli/index.ts is missing the 'git stash push --include-untracked' call"
    grep -q 'hipfire-update-' "$CLI" \
        || fail "cli/index.ts is missing the 'hipfire-update-' stash marker"
    grep -q '"rev-parse", "--verify", "FETCH_HEAD"' "$CLI" \
        || fail "cli/index.ts is missing immutable FETCH_HEAD resolution"
    grep -q '"reset", "--hard", fetched.out' "$CLI" \
        || fail "cli/index.ts is missing the reset to resolved fetched commit"
    grep -q 'rev-list.*--count.*fetched.out.*HEAD' "$CLI" \
        || fail "cli/index.ts is missing the unpushed-commits guard"
    grep -q 'HIPFIRE_INSTALL_REF' "$CLI" \
        || fail "cli/index.ts is missing the explicit install-ref override"
    grep -q 'requested_ref=' "$CLI" \
        || fail "cli/index.ts is missing persisted provenance handling"
    grep -q '"--locked"' "$CLI" \
        || fail "cli/index.ts update builds are not lockfile-enforced"

    # Forbidden: the old buggy call must not be back.
    if grep -E '"pull", *"origin"' "$CLI" >/dev/null; then
        fail "cli/index.ts still contains the buggy 'git pull origin' call"
    fi

    INSTALLER="$REPO_ROOT/scripts/install.sh"
    grep -q 'HUSRCF/hipfire-mit' "$INSTALLER" \
        || fail "install.sh does not default to the clean-room repository"
    grep -q 'HIPFIRE_INSTALL_REF' "$INSTALLER" \
        || fail "install.sh is missing the explicit install-ref override"
    grep -q 'rev-parse --verify FETCH_HEAD' "$INSTALLER" \
        || fail "install.sh does not resolve fetched refs to immutable commits"
    grep -q 'install-source.txt' "$INSTALLER" \
        || fail "install.sh does not persist install provenance"
    grep -q 'cargo build --release --locked' "$INSTALLER" \
        || fail "install.sh build is not lockfile-enforced"
    if grep -q 'Kaden-Schutt/hipfire' "$INSTALLER"; then
        fail "install.sh still points at the post-boundary upstream repository"
    fi
fi

pass "dirty-tree update flow succeeds and preserves changes via stash"
